name: 'TODO Actions Centralized'
description: 'Creates github issues when the exact phrase // TODO: is found. Stores the issues in a centralized repo for easier project planning within an organization.'
branding:
  icon: activity
  color: orange
inputs:
  code-repo-owner: 
    description:
      'The code repo owner, for example: \"OnboardRS\". Assign from `github.repository_owner`.'
    required: true
  code-repo-name:
    description:
      'The code repo repository name, for example: \"github-action-todo-issues-centralized\". Assign from `github.repository`.'
    required: true
  code-repo-branch:
    description:
      'The code repo branch name, for example: \"refs/heads/develop\". Assign from `github.repository.node_id`.'
    required: true
  issue-repo-owner: 
    description:
      'The issue repo owner, for example: \"OnboardRS\". Assign from centralized issue repo.'
    required: true
  issue-repo-name:
    description:
      'The issue repo repository name, for example: \"zenhub-dev\". Assign from centralized issue repo.'
    required: true
  issue-repo-branch:
    description:
      'The issue repo branch name, for example: \"refs/heads/master\". Assign from centralized issue repo.'
    required: true
  issue-labels-csv: 
    description:
      'The issue label(s) TODO GitHub issues should be created with, for example: \"github-actions\". Assign per usage.'
    required: true
  github-action-token: 
    description:
      'The GitHub token with permission to read and change the code. Assign per usage.'
    required: true
  mongo-db-url: 
    description:
      'The Mongo DB Url to use to store TODO hashes. Assign per usage.'
    required: true
  excluded-file-names-csv: 
    description:
      'Comma separated values for case insensitive file names you don't want to search for TODOs. Assign per usage.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--code-repo-owner'
  - ${{ inputs.code-repo-owner }}
  - '--code-repo-name'
  - ${{ inputs.code-repo-name }}
  - '--code-repo-branch'
  - ${{ inputs.code-repo-branch }}
  - '--issue-repo-owner'
  - ${{ inputs.issue-repo-owner }}
  - '--issue-repo-name'
  - ${{ inputs.issue-repo-name }}
  - '--issue-repo-branch'
  - ${{ inputs.issue-repo-branch }}
  - '--issue-labels-csv'
  - ${{ inputs.issue-labels-csv }}
	- '--github-action-token'
  - ${{ inputs.github-action-token }}
	- '--mongo-db-url'
  - ${{ inputs.mongo-db-url }}
  - '--excluded-file-names-csv'
  - ${{ inputs.excluded-file-names-csv }}
