name: Coding Standards

on:
  push:

jobs:
  coding-standards:
    name: Build And Test
    runs-on: ubuntu-latest
    env:      
      solutionName: ./todo-issues-centralized.sln
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2        
      - name: Restore Dependencies
        run: |
          dotnet restore
      - name: Tests
        run: |
          dotnet test --no-restore --filter FullyQualifiedName!~IntegrationTests
      - name: ReSharper CLI InspectCode
        uses: OnboardRS/github-action-resharper-inspect-code@1.0.0
        timeout-minutes: 5
        with:
          solutionPath: ${{ env.solutionName }}
          minimumFailSeverity: warning
          failOnIssue: 1
          minimumReportSeverity: warning    
