name: TODO Centralized
on:
  push:

jobs:
  todo-issues:
    name: Handle TODO ZenHub Issues Integration
    runs-on: ubuntu-latest
    env:
      solutionName: ./todo-issues-centralized.sln
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: TODO Issues Centralized
        uses: OnboardRS/github-action-todo-issues-centralized@develop
        with:
          code-repo-owner: '${{ github.repository_owner }}'
          code-repo-name: '${{ github.repository }}'
          code-repo-branch: '${{ github.ref }}'
          issue-repo-owner: '${{ github.repository_owner }}'
          issue-repo-name: '${{ github.repository }}'
          issue-repo-branch: '${{ github.ref }}'
          issue-labels-csv: 'github-actions'
          github-action-token: '${{ secrets.GITHUB_TOKEN }}'
          mongo-db-url: '${{ secrets.TODO_CENTRALIZED_MONGO_URL }}'
          excluded-file-names-csv: 'Dockerfile,readme.md'
